import turtle
salwas_turtle=turtle.Turtle()
salwas_turtle.speed(5)
color="red"
salwas_turtle.left(90)
salwas_turtle.color(color)
for i in range(3):
    salwas_turtle.right(120)
    salwas_turtle.forward(100)

color="black"
salwas_turtle.right(90)
salwas_turtle.color(color)
salwas_turtle.forward(200)
salwas_turtle.right(90)
salwas_turtle.forward(33.3)
salwas_turtle.right(90)
salwas_turtle.forward(140)
salwas_turtle.penup()
salwas_turtle.left(90)
salwas_turtle.forward(40)
salwas_turtle.pendown()
salwas_turtle.color("green")
salwas_turtle.right(90)
salwas_turtle.back(140)
salwas_turtle.color("#FAF3E0")
salwas_turtle.right(90)
salwas_turtle.forward(39)
salwas_turtle.penup()
salwas_turtle.back(33.3 )
salwas_turtle.pendown()
salwas_turtle.color("green")
salwas_turtle.back(33.3 )
salwas_turtle.left(90)
salwas_turtle.forward(200)